# Generated by Django 5.0.1 on 2024-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='total_request',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
