# Generated by Django 5.0.1 on 2024-02-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_total_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='total_request',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_usage', models.PositiveIntegerField(default=0)),
                ('profile', models.ImageField(upload_to='profile_pic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
